### ISSUE TITLE
ConcurrentPriorityQueue ToArray() bug

### ISSUE THREAD

**Issue by isolet0202** [dshulepov/DataStructures#4]
ToArray() calling CopyTo() making EnterReadLock() called twice.
The exception message is "Recursive read lock acquisitions not allowed in this mode."

Thank you!

**Comment by dshulepov** [comment]
Thanks. ToArray should call base.CopyTo() to avoid double lock entry.
I don't have IDE at hand right now. Do you think you could submit a pull request with a fix and cover it with unit tests?

**Comment by isolet0202** [comment]
I am new to both github and programming. I just tried to add pull requests and hope I did it correctly.
