### ISSUE TITLE
Improving running time of priority queue

### ISSUE THREAD

**Issue by atiq-cs** [dshulepov/DataStructures#8]
Can we use Binomial Heap to improve some operations of the priority queue and overall running time?

[ref](http://www3.cs.stonybrook.edu/~rezaul/Spring-2015/CSE548/CSE548-lectures-16-17-18.pdf)

**Comment by dshulepov** [comment]
Hi
Thanks for the suggestion and a link.
Unfortunately, I don't have time to work on this in any forseeable future, but you can always submit a push request.
Thanks,
Denis
